export enum ActionType {
  AUTH = "AUTH",
  AUTH_SUCCESS = "AUTH_SUCCESS",
  AUTH_FAIL = "AUTH_FAIL",

  GET_NEWS = "GET_NEWS",
  GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS",
  GET_NEWS_FAIL = "GET_NEWS_FAIL",
}
